CREATE TABLE T_ACTION (
  ID        BIGINT AUTO_INCREMENT,
  DS_TICKET VARCHAR(255) NOT NULL COMMENT 'Ticket name',
  DS_TICKET_ACRONYM VARCHAR(255) NOT NULL COMMENT 'Ticket acronym',
  NR_PRICE    DECIMAL(20,2) NOT NULL COMMENT 'Ticket price',
  NR_PRICE_TO_EARNINGS  DECIMAL(20,2) NOT NULL COMMENT 'Ticket price to earnings',
  NR_DIVIDEND_YIELD    DECIMAL(20,2) NOT NULL COMMENT 'Ticket dividend yield ',
  NR_PRICE_PER_BOOK_VALUE    DECIMAL(20,2) NOT NULL COMMENT 'Ticket price per book value',
  NR_ROE    DECIMAL(20,2) NOT NULL COMMENT 'Ticket ROE',
  NR_DAILY_LIQUIDITY    DECIMAL(20,2) NOT NULL COMMENT 'Ticket daily liquidity',
  PRIMARY KEY(ID)
);

CREATE INDEX T_ACTION_search_ticket_index ON T_ACTION(DS_TICKET);